### ISSUE TITLE
Suggestion: Replace TFCond_Bonked with TFCond:106

### ISSUE THREAD

**Issue by Starblaster64** [Chdata/Versus-Saxton-Hale#11]
Line 5271 adds the Bonk! condition to Demomen who lose their shields. Cond 106 is the condition added to players who intercept the Jack in PASS Time. It's basically identical to the Bonk! condition with the following exceptions:
- You can still attack while under the effects of the condition
- All classes will have the translucent trail behind them (Bonk! trail only works for Scout afaik)
- Has an overlay animated distortion effect applied to the player's screen

Probably the lowest priority change ever. I'm suggesting it because of two reasons. One, the very very rare case that someone does try to swing in the 0.1 seconds that the effect is applied for. And two, the fact that it has a distortion overlay effect that would go nicely with the loud sound that's played on losing a shield (even with only a 0.1s duration).
Obviously there are several things to consider (e.g. if the condition will be changed in the future), but I thought I might as well suggest it anyway.

**Comment by Chdata** [comment]
Because of the overlay I'm gonna say no, nobody can feel a 0.1s effect in terms of attacking, and after getting hit by Hale and your shield broken the default action is to retreat and perhaps be 'stunned by his jarring hit'.

If anything I could zero out the damage and TE the miss text above the demo's head, but it works fine as is. Might even be better to give the game the extra frames to process that the demo's shield was broken without letting him attack.

I have one boss that tries to switch your melee weapon in the middle of attacking if you miss, and sometimes the model doesn't update perfectly until you stop.

**Comment by Starblaster64** [comment]
Fair enough, closing suggestion.
